name = "auraly-voice"
compatibility_date = "2025-10-24"
pages_build_output_dir = "./public"

[[r2_buckets]]
binding     = "AUDIO"
bucket_name = "auraly-audio"

[env.preview.vars]
NEXT_PUBLIC_TURNSTILE_SITE_KEY = "1x00000000000000000000AA"
[[env.preview.r2_buckets]]
binding     = "AUDIO"
bucket_name = "auraly-audio"

[env.production.vars]
NEXT_PUBLIC_TURNSTILE_SITE_KEY = "1x00000000000000000000AA"
[[env.production.r2_buckets]]
binding     = "AUDIO"
bucket_name = "auraly-audio"

# Worker Rate Limiting (5 requests per 60s)
[[env.preview.ratelimits]]
name = "UPLOAD_LIMIT"
namespace_id = "7001"
simple = { limit = 5, period = 60 }

[[env.production.ratelimits]]
name = "UPLOAD_LIMIT"
namespace_id = "7001"
simple = { limit = 5, period = 60 }
