name = "auraly-voice"                 # MUST equal your Pages project name
compatibility_date = "2025-10-24"
pages_build_output_dir = "./public"   # Required by Pages

# Do NOT store production secrets in source control.

# R2 binding (top-level)
[[r2_buckets]]
binding     = "AUDIO"
bucket_name = "auraly-audio"

# ---- Preview (keeps Turnstile on test keys) ----
[env.preview.vars]
NEXT_PUBLIC_TURNSTILE_SITE_KEY = "1x00000000000000000000AA"  # official test site key

[[env.preview.r2_buckets]]
binding     = "AUDIO"
bucket_name = "auraly-audio"

# ---- Production (uses your REAL site key) ----
[env.production.vars]
NEXT_PUBLIC_TURNSTILE_SITE_KEY = "0x4AAAAAAB8kxanXAZMswmOT"

[[env.production.r2_buckets]]
binding     = "AUDIO"
bucket_name = "auraly-audio"
