name = "auraly-voice"
compatibility_date = "2025-10-24"
pages_build_output_dir = "./public"

[[r2_buckets]]
binding     = "AUDIO"
bucket_name = "auraly-audio"

[env.preview.vars]
NEXT_PUBLIC_TURNSTILE_SITE_KEY = "1x00000000000000000000AA"
TURNSTILE_SECRET_KEY            = "1x0000000000000000000000000000000AA"
[[env.preview.r2_buckets]]
binding     = "AUDIO"
bucket_name = "auraly-audio"

[env.production.vars]
NEXT_PUBLIC_TURNSTILE_SITE_KEY = "0x4AAAAAAB8kxanXAZMswmOT"
[[env.production.r2_buckets]]
binding     = "AUDIO"
bucket_name = "auraly-audio"
