name = "auraly-pages"
compatibility_date = "2025-10-24"
pages_build_output_dir = "./public"

[[r2_buckets]]
binding = "AUDIO"
bucket_name = "auraly-audio"

[vars]
NEXT_PUBLIC_TURNSTILE_SITE_KEY = "1x00000000000000000000AA"        # Turnstile test site key (always passes)
TURNSTILE_SECRET_KEY            = "1x0000000000000000000000000000000AA"  # Turnstile test secret (always passes)
