name = "auraly-voice"
compatibility_date = "2025-10-24"
pages_build_output_dir = "./public"

[ai]
binding = "AI"   # Workers AI binding (env.AI)

[[r2_buckets]]
binding     = "AUDIO"
bucket_name = "auraly-audio"

[[d1_databases]]
binding        = "DB"
database_name  = "auraly-db"
database_id    = "2549f08a-21a9-4c54-ae87-69a8f34817d7"

[env.preview.vars]
NEXT_PUBLIC_TURNSTILE_SITE_KEY = "1x00000000000000000000AA"
TURNSTILE_SECRET_KEY            = "1x0000000000000000000000000000000AA"
[[env.preview.r2_buckets]]
binding     = "AUDIO"
bucket_name = "auraly-audio"
[[env.preview.d1_databases]]
binding        = "DB"
database_name  = "auraly-db"
database_id    = "2549f08a-21a9-4c54-ae87-69a8f34817d7"

[env.production.vars]
NEXT_PUBLIC_TURNSTILE_SITE_KEY = "1x00000000000000000000AA"
[[env.production.r2_buckets]]
binding     = "AUDIO"
bucket_name = "auraly-audio"
[[env.production.d1_databases]]
binding        = "DB"
database_name  = "auraly-db"
database_id    = "2549f08a-21a9-4c54-ae87-69a8f34817d7"
